Make this a vanilla installer to be used by non-devs as well (#3)
* Refactor and simplify install script (use pre-built ARM binary) and remove all dependencies (go, git etc.)
* Create uninstall script
* Exit with failure code 1 everywhere for consistency
* Allow installer to accept IPFS version as first parameter
* Allow installer to accept arch type as second parameter
* Remove template file and write systemctl configs directly in the installer

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,101 +1,76 @@
 #!/usr/bin/env bash
 
-set -o errexit
 set -o pipefail
 
-if [ -x "$(command -v ipfs)" ]; then
-    echo "IPFS already installed"
-    exit 0
+#
+[ -x "$(command -v ipfs)" ] && echo ">>> IPFS already installed. Use the uninstall script to remove it" && exit 0
+
+#
+arm_type="unknown ARM system"
+rpi_revision=`sed -rn 's/Revision\s+\:\s+([0-9a-z_\-\s\,\(\)]+)/\1/p' /proc/cpuinfo`
+
+if [[ $rpi_revision == *"900092"* ]]; then
+  arm_type="Raspberry Pi model zero"
+elif [[ $rpi_revision == *"00"* ]]; then
+  arm_type="Raspberry Pi 1"
+elif [[ $rpi_revision == *"a01041"* || $rpi_revision == *"a21041"* ]]; then
+  arm_type="Raspberry Pi 2"
+elif [[ $rpi_revision == *"a02082"* || $rpi_revision = *"a22082"* ]]; then
+  arm_type="Raspberry Pi 3"
 fi
 
-RPI_REVISION=`sed -rn 's/Revision\s+\:\s+([0-9a-z_\-\s\,\(\)]+)/\1/p' /proc/cpuinfo`
+echo ">>> Starting installation on $arm_type"
 
-if [[ $RPI_REVISION == *"900092"* ]]; then
-    echo ">>> This Raspberry Pi model (zero) hasn't been tested yet"
-    exit 0
-elif [[ $RPI_REVISION == *"00"* ]]; then
-    echo ">>> Starting installation on Raspberry Pi 1..."
-elif [[ $RPI_REVISION == *"a01041"* || $RPI_REVISION == *"a21041"* ]]; then
-    echo ">>> Starting installation on Raspberry Pi 2..."
-elif [[ $RPI_REVISION == *"a02082"* || $RPI_REVISION = *"a22082"* ]]; then
-    echo -e ">>> Starting installation on Raspberry Pi 3...\n"
-else
-    echo ">>> Unknown Raspberry Pi model"
-    exit 1
+# Download and install IPFS
+ipfs_arch=${2-"linux-arm"}
+ipfs_version=${1-"v0.4.13"}
+
+echo ">>> Installing IPFS version $ipfs_version"
+
+tar_gz_destination=/tmp/go-ipfs_${ipfs_version}_${ipfs_arch}.tar.gz
+[ ! -f $tar_gz_destination ] && sudo wget "https://dist.ipfs.io/go-ipfs/${ipfs_version}/go-ipfs_${ipfs_version}_${ipfs_arch}.tar.gz" -O $tar_gz_destination
+
+if [ ! -f $tar_gz_destination ]; then
+  echo ">>> Failed to download IPFS"
+  exit 1
 fi
 
-sudo apt-get update
-sudo apt-get -y install \
-    nodejs \
-    git
+ipfs_destination=/usr/local/bin/ipfs
+sudo tar xzvf $tar_gz_destination -C /tmp
+sudo cp /tmp/go-ipfs/ipfs $ipfs_destination
+sudo chown root:staff $ipfs_destination
+sudo chmod 755 $ipfs_destination
 
-# Maybe install Go from source (IPFS requires Go 1.8+)
-GOROOT_PARENT=/usr/local
-if [ ! -x "$(command -v go)" ]; then
-    GO_VERSION=1.9
-    echo ">>> Installing Go $GO_VERSION"
-    GO_PKG="go$GO_VERSION.linux-armv6l.tar.gz"
-    if [ ! -f $GO_PKG ]; then
-        wget "https://storage.googleapis.com/golang/$GO_PKG"
-    fi
+# Maybe initialize IPFS
+[ ! -d ~/.ipfs ] && ipfs init
 
-    sudo tar -xzf $GO_PKG -C $GOROOT_PARENT
-else
-    CURRENT_GO_VERSION="$(go version 2>/dev/null | sed -n 's/^go version go\([^ ]*\) .*$/\1/p')"
-    echo ">>> Go alredy installed. Version: $CURRENT_GO_VERSION"
-    if [[ -n "$CURRENT_GO_VERSION" ]]; then
-        IFS='.' read -r -a CURRENT_GO_VERSION_ARRAY <<< $CURRENT_GO_VERSION
-        if [ "${CURRENT_GO_VERSION_ARRAY[0]}""${CURRENT_GO_VERSION_ARRAY[1]}" -lt "18" ]; then
-            echo ">>> Current Go version is incompatible with IPFS. Please uninstall Go and run this script again."
-            exit 0
-        fi
-    fi
-fi
+# Maybe install and enable bring-up configurations for IPFS daemon
+if [ ! -f /lib/systemd/system/ipfs-daemon.service ]; then
+  cat << EOF | sudo tee /lib/systemd/system/ipfs-daemon.service
+[Unit]
+Description=IPFS daemon
+Wants=network.target
+After=network.target
 
-# Set up Go environment
-GOROOT=$GOROOT_PARENT/go
-GO_PROFILE_PATH=/etc/profile.d/golang.sh
+[Service]
+Type=simple
+Environment=IPFS_PATH=$HOME/.ipfs
+ExecStart=/usr/local/bin/ipfs daemon
+ExecStop=/usr/bin/pkill -f ipfs
+Restart=on-failure
+RestartSec=10s
 
-sudo tee $GO_PROFILE_PATH <<EOF
-export GOROOT=$GOROOT
-export PATH=\$PATH:\$GOROOT/bin
+[Install]
+WantedBy=multi-user.target
 EOF
 
-. $GO_PROFILE_PATH
-sudo chgrp -R staff $GOROOT
-
-export GOPATH=$HOME/go
-if [ ! -d "$GOPATH" ]; then
-    mkdir $GOPATH
-    echo ">>> GOPATH created at $GOPATH"
-else
-    echo ">>> GOPATH = $GOPATH"
 fi
-
-if ! grep --quiet "\$GOPATH" $HOME/.bashrc; then
-    echo -e "\nexport GOPATH=$GOPATH" >> $HOME/.bashrc
-    echo -e "export PATH=\$PATH:\$GOPATH/bin" >> $HOME/.bashrc
-fi
-
-# Install IPFS
-echo ">>> Installing IPFS"
-GO_EXEC=$GOROOT/bin/go
-$GO_EXEC get -u -d github.com/ipfs/go-ipfs
-cd $GOPATH/src/github.com/ipfs/go-ipfs
-make install
-cd -
-sudo cp ~/go/bin/ipfs /usr/local/bin/ipfs
-
-# Initialize IPFS
-IPFS_EXEC=$GOPATH/bin/ipfs
-$IPFS_EXEC init
-
-# Install and enable bring-up configurations for IPFS daemon
-sudo cp ipfs-daemon.service /etc/systemd/system/ipfs-daemon.service
-sudo systemctl enable ipfs-daemon.service
 
 # Start IPFS daemon
+sudo systemctl daemon-reload
+sudo systemctl enable ipfs-daemon
 sudo systemctl start ipfs-daemon.service
 
-echo -e "\n>>> All done"
+#
+echo ">>> All done."
 
